version: '3.8'

services:
  app:
    user: root
    image: jenkins/jenkins:alpine-jdk11
    volumes:
      - data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    extra_hosts:
      - sonar.juferoga.tk:IP
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.jenkins.entrypoints=websecure"
        - "traefik.http.routers.jenkins.rule=Host(`jenkins.juferoga.tk`)"
        - "traefik.http.routers.jenkins.service=jenkins"
        - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == juferoga.tk]

networks:
  proxy:
    external: true

volumes:
  data:
